### ISSUE TITLE
Node v14.x support

### ISSUE THREAD

**Issue by tlhfckoctbcr** [Foo-Foo-MQ/foo-foo-mq#17]
Good morning! Would it be possible for `foo-foo-mq` to run in Node v14.x without ignoring the engine range specified in the `package.json`? My team is swapping to this module from the unsupported `rabbot`. We use Yarn as our package manager, which errors whenever we attempt to install the module locally. We could add a flag to ignore the engine suggested, but would prefer to ask you first about whether or not the module can run successfully on v14. Thank you.

**Comment by zlintz** [comment]
The foo-foo-mq code itself should be able to run on node 14, but a quick test shows that the current version of amqplib it is using doesn't support node 14 so that will need to get updated first. Seems like it is time to get this running on 14 anyways

**Comment by tlhfckoctbcr** [comment]
Right on, we'll keep an eye out for the update. Thanks again.

**Comment by zlintz** [comment]
Might take a couple days depending on my time. There are few additional dependencies that also require new releases to confirm work on 14, you can follow progress on this PR https://github.com/Foo-Foo-MQ/foo-foo-mq/pull/18

**Comment by tlhfckoctbcr** [comment]
Sweet! Def doesn't need to happen overnight. 👍🏻

**Comment by auroq** [comment]
This was just released in 5.0.0.

**Comment by tlhfckoctbcr** [comment]
Thanks, guys. Great stuff.
