### ISSUE TITLE
Migrating from rabbot

### ISSUE THREAD

**Issue by behrad** [Foo-Foo-MQ/foo-foo-mq#21]
Can you please elaborate on migrating from rabbot in production?

Does switching to require('foo-foo-mq') make it happen with current code? I couldn't find any related guide.

**Comment by zlintz** [comment]
Hello @behrad 
I think what you are looking for is the CHANGELOG.md file starting here https://github.com/Foo-Foo-MQ/foo-foo-mq/blob/master/CHANGELOG.md#300 

But the short answer is...

- `3.0.0` is straight across update, no difference from `2.1.0` of rabbot

- `5.0.0` is current and if you are node 10-14 then that should also be non breaking 

That said, please take a look at that changelog for more details

**Comment by behrad** [comment]
Great @zlintz thank you for your clarification.
