### ISSUE TITLE
Correct protocol is 'amqp', not 'amqp://'

### ISSUE THREAD

**Issue by mick62** [Foo-Foo-MQ/foo-foo-mq#26]
Hi,
The official definition of 'protocol' is the name of the protocol. So the correct protocol value is 'amqp'.
Currently foo-foo-mq can't establish a connection when given 'amqp' as the protocol in the connection configuration.

Please change the behavior to allow 'amqp' (as well as 'amqp://' for backward compatibility) for the protocol in the connection configuration.

Thanks for your great work.

**Comment by zlintz** [comment]
@mick62 sounds like you know what to do here. Any interest in contributing a PR and tests for this?

**Comment by mick62** [comment]
I would really enjoy to contribute but unfortunately I'm 200% overloaded with other projects.

**Comment by zlintz** [comment]
@mick62 I am as well, as you can see its been sitting here for awhile (I have a FT job and family first). This is just a side project for me, ie I currently get nothing for this other than the fact I like rabbitmq and would like to help as I can/time allows. If I get time I will look into this but I am looking to the community for help with active changes and fixes.

**Comment by MartianH** [comment]
@zlintz I am working on a pull request for this and my own issue (#55 )

**Comment by MartianH** [comment]
@zlintz  can this ticket be closed now?

**Comment by zlintz** [comment]
Fixed by @MartianH in v9.1.0
