### ISSUE TITLE
Cannot use foo-foo-mq for node 16

### ISSUE THREAD

**Issue by adriantam** [Foo-Foo-MQ/foo-foo-mq#28]
Now that node v15 (https://nodejs.org/en/about/releases/) is EOL and v16 is active, foo-foo-mq should support node v16.

However,  package.json current specifies to support "node": ">=10 <=15"

**Comment by zlintz** [comment]
@auroq Looks like it's time for another upgrade of `amqplib` in order to allow supporting node v16.  The nice thing is it looks like they have removed the upper limit node restriction they used to do in versions < 0.8.0

**Comment by adriantam** [comment]
https://github.com/Foo-Foo-MQ/node-monologue also needs to be updated to allow node v16.
See https://github.com/Foo-Foo-MQ/node-monologue/blob/main/package.json#L70

**Comment by auroq** [comment]
Thanks for bringing this to our attention, @adriantam! We'll get this done as soon as we can.

**Comment by auroq** [comment]
@adriantam, this is now published as part of 7.0.0: https://www.npmjs.com/package/foo-foo-mq/v/7.0.0
