### ISSUE TITLE
How to set custom appId

### ISSUE THREAD

**Issue by scipe** [Foo-Foo-MQ/foo-foo-mq#35]
Hey folks! How can I set the custom appId?

**Comment by zlintz** [comment]
@scipe thanks for the question,  can you give some more context. I think I am missing something you are trying to do.

**Comment by scipe** [comment]
I don't really remember :) 
But I think it was for tracing and inside AppId I wanted to put the application name + version. And rabbitmq protocol supporting this.

**Comment by zlintz** [comment]
Please reopen if this is still a problem/concern. Seems both of us are busy otherwise
