### ISSUE TITLE
Support for node 18?

### ISSUE THREAD

**Issue by MartianH** [Foo-Foo-MQ/foo-foo-mq#37]
Greetings,

The package.json ([line 8)](https://github.com/Foo-Foo-MQ/foo-foo-mq/blob/f07b86f21c71e31dd47987b2b514151ab6631cd5/package.json#L8) stipulate it only support node 12 up to and including 16.
Considering v18 is about to reach Active LTS in a few months, I wonder if this could be changed. The issue now is that it is breaking my docker build due to the incompatible engines (`node:18-alpine`).

**Comment by zlintz** [comment]
I started looking into node 18 but haven't had much time. Something in the tests are currently breaking when moving up to node 18.

Do you mind trying to run the tests as well while using node 18?
