### ISSUE TITLE
Some properties are not supported by foo-foo-mq ( eg. priority )

### ISSUE THREAD

**Issue by shifubrams** [Foo-Foo-MQ/foo-foo-mq#46]
Hello, 
in the documentation, [here](https://github.com/Foo-Foo-MQ/foo-foo-mq/blob/main/docs/publishing.md#example), it is mentionned that all the properties available are in this example. But, i tried to put priority ( enforced the typing ) and it ignores it. 

Is it possible to manage priority as the package is ? 
If not, can you please add this field to the publish options ? 

List of the supported rabbitmq properties : 
<img width="915" alt="image" src="https://user-images.githubusercontent.com/26507906/235628765-d27c1b98-91ef-4a22-8c22-e9661885671a.png">

Example : 
```typescript  
try {
      await this.rabbit.publish("my-exchange", {
        priority: 7, // tried to put the property in the root of options
        properties: {
          priority: 5  // tried to put the property in a "properties" field of options
        },
        headers: {priority: "10"}, // tried to put the property as a header field, it's added but not considered as a property
        body: { "f1":"v1" },
      } as PublishOptions);
} catch (error) {
       console.log(error);
}
```
This example above gives this message in rabbit : 
<img width="613" alt="image" src="https://user-images.githubusercontent.com/26507906/235631310-1a1b28db-a330-48e5-a6d8-a26ebdc24d31.png">

Using : 
rabbitmq : v3.8.3
foo-foo-mq : v8.0.0
NodeJS : 18

**Comment by shifubrams** [comment]
a solution would be to append this object 
https://github.com/Foo-Foo-MQ/foo-foo-mq/blob/e492c72d89f871b16ecf80f749e76d8e95097900/src/amqp/exchange.js#L79
 to take in account the official properties like priority. ( tested and working ). 
 
``` typescript
  const publishOptions = {
    type: message.type || '',
    contentType: contentType,
    contentEncoding: 'utf8',
    correlationId: message.correlationId || '',
    replyTo: message.replyTo || topology.replyQueue.name || '',
    messageId: message.messageId || message.id || '',
    timestamp: message.timestamp || Date.now(),
    appId: message.appId || info.id,
    headers: message.headers || {},
    expiration: message.expiresAfter || undefined,
    mandatory: message.mandatory || false,
    priority: message.priority || undefined
  };
```

**Comment by zlintz** [comment]
@shifubrams please open a pull request for this

**Comment by zlintz** [comment]
Also if you don't mind including the appropriate documentation updates that would be great

**Comment by shifubrams** [comment]
@zlintz  can we just open a branch on this repo to avoid forking the whole repo ? I get a 403 when i want to push my branch

**Comment by shifubrams** [comment]
can i have a follow up on this please ?

**Comment by zlintz** [comment]
Sure I’ll take a look at the repo settings today.

**Comment by zlintz** [comment]
You should be able to now

**Comment by shifubrams** [comment]
hello, 
sorry i was able to create the branch but not to push on it. 

![image](https://github.com/Foo-Foo-MQ/foo-foo-mq/assets/26507906/9e24e3db-c140-4b43-a6d6-1ef95a2363b9)
